# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  ARTIFACT_NAME: ifc2rdftool

permissions:
  contents: read

jobs:
  build-for-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run lint
      run: |
        pylint ifc2rdftool
    - name: Run tests
      run: |
        pytest
    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .

  build-for-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if (Test-Path requirements.txt) {
          pip install -r requirements.txt
        }
    - name: Run lint
      run: |
        pylint ifc2rdftool
    - name: Run tests
      run: |
        pytest

  build-for-macos:

        runs-on: macos-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
              python-version: "3.10"
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install pylint pytest
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Run lint
          run: |
              pylint ifc2rdftool
        - name: Run tests
          run: |
              pytest
